### ISSUE TITLE
request's entityId field for GET, PUT, DELETE queries by id

### ISSUE THREAD

**Issue by egkozlov** [Kinvey/business-logic-testing-library#2]
I'm trying to test Kinvey GET, PUT, DELETE by id requests which looks like 
GET,PUT,DELETE /appdata/:appKey/:collectionName/:id
In Kinvey hook methods we can get :id value from request's entityId field. The problem is that I can't sent this field using Mock request. I tried next

``` javascript
var requestObject = tester.createMockRequest({entityId: "564d093190406e824f04c521"});
```

but without success. 
Is "entityId" field supported?

**Comment by amoothart** [comment]
Yegor: go ahead and mention me when you have questions on unit testing: @amoothart I will try to help you with any questions here along with the Kinvey engineering team.

You can create mock requests by passing in a JSON object as the request body: https://github.com/Kinvey/business-logic-testing-library#mock-request-builder var requestObject = tester.createMockRequest({ body: { testing: true }});

You can also do this with the setBody method: https://github.com/Kinvey/business-logic-testing-library#setbodyjsonobject

entityId is automatically found from the _id field in the json body: http://devcenter.kinvey.com/rest/reference/business-logic/reference.html#request

You can then execute the request using: https://github.com/Kinvey/business-logic-testing-library#runcollectionhookcollectionname-blfunctionname-requestobject-responseobject-callback client.runCollectionHook('MyCollection', 'onPreSave', requestObject, responseObject, function(error, blResult)

**Comment by egkozlov** [comment]
@amoothart I've added json body with _id to request object but without success

> entityId is automatically found from the _id field in the json body: http://devcenter.kinvey.com/rest/reference/business-logic/reference.html#request

I've tried next code for request object:

``` javascript
      requestObject = tester.createMockRequest();
            var body = {
                "_id": "564d093190406e824f04c521"
            };
            requestObject.setBody(body);
            requestObject.addHeader('x-kinvey-api-version', 3);
            requestObject.setAuthenticatedUsername('testUser1');
```

But entityId field didn't appear in request object.
Request object has the next view:

``` json
{
    "method": "DELETE",
    "headers": {"x-kinvey-api-version": 3, "X-Kinvey-Custom-Request-Properties": "{}"},
    "body": {"_id": "564d093190406e824f04c521"},
    "params": {},
    "username": "testUser1",
    "collectionName": "UserRelationship",
    "appKey": "kid_-k8AUP2hw",
    "tempObjectStore": {}
}
```

**Comment by amoothart** [comment]
Ok, we're closer. The next step will be to set the id in the request parameter. requestObject.addParam(‘id’, body._id)

This will work for GET/PUT/DELETE but as normal you will need a full request body for PUT and DELETE calls.

I assume you're using runCollectionHook to execute your test right?

**Comment by egkozlov** [comment]
--> The next step will be to set the id in the request parameter. requestObject.addParam(‘id’, body._id)
It solves the problem. Thanks

--> I assume you're using runCollectionHook to execute your test right?
Yes
