### ISSUE TITLE
collection member function is not called

### ISSUE THREAD

**Issue by ali5h** [Kinvey/business-logic-testing-library#5]
I am starting to write tests for our backend, but what ever I try, collection functions such as `findOneAsync` or `findOne` are never executed and the request times out. I have populated data  to the collection in the test script (tested with `getCollectionData`). This is the test endpoint I created.  Here `circles.findOneAsync` is never executed. The script itself is executed, since I can add `response.error` to the end and get the error, but otherwise it times out.

```
onRequest = function(request, response, modules) {
  var circle, circles;
  circles = modules.collectionAccess.collection('circles');
  circle = request.body;
  circles.findOneAsync({
    _id: circle._id
  }).then(function(result) {
    if (result == null) {
      return response.error("circle not found");
    }
    return response.complete();
  }, function(err) {
    return response.error(err);
  });
  // return response.error("Should not be here");
};
```

**Comment by vseventer** [comment]
@shariat - Apologies for the late response, not sure if this is a problem but I'll try to help out.

You mentioned the code you provided is part of a custom endpoint right? In that context, using `response.continue` is not allowed, and you should use `response.complete` instead.

Not positive this is the actual problem you are facing, normally this should cause the test to fail with the `UnallowedError: Method 'response.continue' is not allowed in this context.` error. If not, can you show me your test code?

**Comment by ali5h** [comment]
I am using response.complete, sorry for the mistake here. I am using kinvey templates generated by the command line. 

```
var path = require('path');
var mongodb = require('mongodb');
// Package modules.
var tester = require('kinvey-business-logic-testing-library');

// Configure.
var options = {
  blRootPath: path.join(__dirname, '../../../deploy/business-logic'),
  environmentID: "test",
  containerHostOrIP: "docker_host_ip"
};

// Test suite.
describe('kinvey backend', function() {
  // Set-up the client.
  before('client', function(cb) {
    this.timeout(0); // Disable timeout.
    var self = this;
    tester.util.setup(options, function(err, client) {
      self.client = client; // Save.
      cb(err); // Continue.
    });
  });

  // Set the endpoint under test.
  before('configure', function() {
    this.endpoint = 'test';
    this.collection = 'circles'
  });

  before('populate', function(cb) {
    var data = [{
      "_id": "54613fc98192b34c34f972ee",
      "center": {
        "_type": "KinveyRef",
        "_id": "56a9e97939cb31026f016906",
        "_collection": "user"
      },
      "members": [
        {
          "_type": "KinveyRef",
          "_id": "56a9e97939cb31026f016906",
          "_collection": "user"
        },
        {
          "_type": "KinveyRef",
          "_id": "52bdb64e4b745ee12dc25b43",
          "_collection": "user"
        },
      ]
    }];
    this.client.dataStore.importCollectionData(this.circles, data, true, cb);
  });

  after('configure', function() {
    delete this.endpoint; // Cleanup.
  });

  // Teardown the client.
  after('client', function(cb) {
    delete this.client; // Cleanup.
    tester.util.teardown(options, cb);
  });

  // Tests.
  it('should be able to run a test endpoint', function(done) {
    // Configure the request.
    var requestObject = {
      body: {
        action: "test",
        _id: "54613fc98192b34c34f972ee"
      }
    };

    // Run the endpoint.
    this.client.runCustomEndpoint(this.endpoint,
      requestObject, { }, function(err, blResult) {
        done(err); // Continue.
      });
  });
});
```

**Comment by vseventer** [comment]
I tried running the code you provided, and apart from having to make a little change (line 51 of the test script should be `this.client.dataStore.importCollectionData(this.collection, data, true, cb);`), the test passes.

So, I am not sure what's going on. Does the test consistently time out?

**Comment by ali5h** [comment]
Not always, I noticed the first time the tests bring up the docker containers the result is different. Which means the find function is executed, but there was no data in the db. Subsequent calls will timeout.

```
Error: done() invoked with non-Error: {
  "isError":true,
  "message":"Runtime Exception",
  "debugMessage":"UserDefinedError: circle not found",
  "metadata":
    {"hookType":"customEndpoint",
     "collectionName":"test",
     "targetFunction":"onRequest",
     "taskId":"13c02160-5325-4184-ae10-c51ba5db5b0b","unhandled":true},
     "endOnComplete":false,
     "rusage":
       {"utime":0.010000000000000009,
        "stime":0.01999999999999999,
        "maxrss":17944,
"ixrss":0,"idrss":0,"isrss":0,"minflt":395,"majflt":0,
"nswap":0,"inblock":0,"oublock":0,"msgsnd":0,
"msgrcv":0,"nsignals":0,"nvcsw":11,"nivcsw":8,
"wtime":0.1399998664855957},
"taskId":"13c02160-5325-4184-ae10-c51ba5db5b0b"}
```

**Comment by vseventer** [comment]
Tricky issue. When calls timeout, does the test suite report the timeout error? Also, would it be possible to share a repository containing the tests (I tried running the exact code you provided, but didn't find any errors).

**Comment by cmolina** [comment]
I am experiencing the same problem with `findOneAsync`, actually it seems that never connect to the database.
This is the error from `findOneAsync`:

``` javascript
{ cause: 
   { code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect' },
  isOperational: true,
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

 @shariat did you find any workaround?

**Comment by ali5h** [comment]
I haven't got time to investigate this fully yet

**Comment by ali5h** [comment]
I cannot reproduce this after recreating the docker machine
